In [8]:
import pandas as pd
import os
import numpy as np
from matplotlib import pyplot as plt
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.cluster import KMeans

In [2]:
file_0 = pd.read_csv("C:/Users/tanji/Desktop/safety/features/part-00000-e6120af0-10c2-4248-97c4-81baf4304e5c-c000.csv")
file_1 = pd.read_csv("C:/Users/tanji/Desktop/safety/features/part-00001-e6120af0-10c2-4248-97c4-81baf4304e5c-c000.csv")
file_2 = pd.read_csv("C:/Users/tanji/Desktop/safety/features/part-00002-e6120af0-10c2-4248-97c4-81baf4304e5c-c000.csv")
file_3 = pd.read_csv("C:/Users/tanji/Desktop/safety/features/part-00003-e6120af0-10c2-4248-97c4-81baf4304e5c-c000.csv")
file_4 = pd.read_csv("C:/Users/tanji/Desktop/safety/features/part-00004-e6120af0-10c2-4248-97c4-81baf4304e5c-c000.csv")
file_5 = pd.read_csv("C:/Users/tanji/Desktop/safety/features/part-00005-e6120af0-10c2-4248-97c4-81baf4304e5c-c000.csv")
file_6 = pd.read_csv("C:/Users/tanji/Desktop/safety/features/part-00006-e6120af0-10c2-4248-97c4-81baf4304e5c-c000.csv")
file_7 = pd.read_csv("C:/Users/tanji/Desktop/safety/features/part-00007-e6120af0-10c2-4248-97c4-81baf4304e5c-c000.csv")
file_8 = pd.read_csv("C:/Users/tanji/Desktop/safety/features/part-00008-e6120af0-10c2-4248-97c4-81baf4304e5c-c000.csv")
file_9 = pd.read_csv("C:/Users/tanji/Desktop/safety/features/part-00009-e6120af0-10c2-4248-97c4-81baf4304e5c-c000.csv")
labels_0 = pd.read_csv("C:/Users/tanji/Desktop/safety/labels/part-00000-e9445087-aa0a-433b-a7f6-7f4c19d78ad6-c000.csv")

In [3]:
#Removal of duplicated rows in labels dataframe
labels_0 = pd.read_csv("C:/Users/tanji/Desktop/safety/labels/part-00000-e9445087-aa0a-433b-a7f6-7f4c19d78ad6-c000.csv")
labels_0 = labels_0.groupby('bookingID', group_keys=True).apply(lambda x: x.loc[x.label.idxmax()])
labels_0 = labels_0.rename_axis(None)

In [4]:
frames = [file_0, file_1, file_2, file_3, file_4, file_5, file_6, file_7, file_8, file_9]
main_df = pd.concat(frames)
main_df = main_df.sort_values(by=['bookingID', 'second'])

In [22]:
file_0 = file_0.sort_values(by=['bookingID', 'second'])
X = []
for name, group in file_0.groupby("bookingID"):
    #print(group['Speed'])
    temp_arr = []
    for index, row in group.iterrows():
        temp_arr.append(row['Speed'])
    X.append(temp_arr)
    
X = np.array(X)
#this is your array with the values
#X = np.array([[1, 2], [1, 4], [1, 0],[4, 2], [4, 4], [4, 0]])


#This function creates the classifier
#n_clusters is the number of clusters you want to use to classify your data
kmeans = KMeans(n_clusters=2, random_state=0).fit(X)

#you can see the labels with:
print(kmeans.labels_)

# the output will be something like:
#array([0, 0, 0, 1, 1, 1], dtype=int32)
# the values (0,1) tell you to what cluster does every of your data points correspond to

#You can predict new points with
kmeans.predict([[0, 0], [4, 4]])

#array([0, 1], dtype=int32)

#or see were the centres of your clusters are
kmeans.cluster_centers_
#array([[ 1.,  2.],
#     [ 4.,  2.]])

ValueError: setting an array element with a sequence.

In [23]:
for element in X:
    print(element)

[0.22845447063446045, 0.22845447063446045, 0.2977951765060425, 0.2977951765060425, 0.2977951765060425, 0.13761885464191434, 0.13761885464191434, 0.13761885464191434, 3.882817268371582, 14.252004623413086, 13.896020889282227, 13.415084838867188, 13.093417167663574, 11.216825485229492, 0.45492699742317205, 0.22789128124713895, 0.22789128124713895, 2.3505725860595703, 5.945220470428468, 5.8142127990722665, 5.172356128692627, 2.9472031593322754, 5.28489351272583, 3.7283971309661865, 3.824497222900391, 0.1624259501695633, 0.1624259501695633, 0.1624259501695633, 0.0643085241317749, 4.2958927154541025, 5.726363658905028, 1.6356840133666992, 4.3861474990844735, 5.8462653160095215, 13.01933765411377, 13.518714904785154, 12.606927871704102, 10.436896324157717, 5.239145755767822, 0.06751469522714615, 0.06751469522714615, 0.06751469522714615, 0.06751469522714615, 0.06751469522714615, 3.123471736907959, 6.979379177093506, 11.528499603271484, 4.2175917625427255, 4.2175917625427255, 5.901721477508545

[0.0, 0.0, 1.3770368999999998, 1.0432185999999999, 0.0, 0.0, 16.095823, 15.968573999999998, 11.430177, 12.402974, 13.180515, 14.251382999999999, 13.945113000000001, 5.5561739999999995, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.1765616000000003, 2.8652437, 4.1678996, 3.3507843, 7.1197667000000004, 6.680852000000001, 7.028434299999999, 10.600515, 10.952616, 0.0, 0.0, 0.0, 11.907200999999999, 7.072271000000001, 15.343819, 13.409208999999999, 19.12753, 26.652699, 24.946795, 24.832155, 25.439478, 26.271168, 26.493603000000004, 26.663666, 27.180325, 27.091919, 23.026173, 17.792755, 19.722551, 18.36886, 24.448726999999998, 24.054873, 22.775185, 23.275595000000003, 24.237667000000002, 25.81992, 25.62133, 24.278267, 23.955915, 24.059488, 23.726633, 24.966076, 24.89854]
[2.8013337000000003, 4.676665, 3.5979302000000004, -1.0, 5.593322799999999, 6.1062959999999995, 0.0, 0.0, 2.3132427000000004, 3.5026116000000003, 4.814447400000001, 0.69494957, 0.0, 3.5762832, 4.861053, 12.720072, 13.43246, 

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

